name: build-publish-master-container

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
 test:
    name: test
    runs-on: ubuntu-latest

    steps:
    - name: Get datatlasRepo
      uses: actions/checkout@v2
      with:
        repository: datatlas-erasme/front
        run: ls

  
